### ISSUE TITLE
Question: Converting Base16 to Base24

### ISSUE THREAD

**Issue by MrDowntempo** [FredHappyface/FredHappyface#1]
Hi, I'm a little confused about the way Base24 works. I'm looking to expand a Base16 theme into a Base24 one so that I have the 8 additional colors needed for ANSI terminals. Not exactly sure which tool calculates what those 8 additional colors should be (which is what I expected to find but I could be way off base) Thanks for any help!

**Comment by FredHappyface** [comment]
This repo has some tools to help with base24 theme generation https://github.com/Base24/base24-helpers

I thought I had created a tool to generate base24 themes from base16 themes but this appears not to the the case. You are welcome to open a pr if you have any code that you think could be helpful

Going to close this issue though as I currently have no plans to add this functionality
